from random import shuffle

def embaralhar():
    Figurinhas_Sapos_de_Chocolate = [
        ('1', 'Merlín'),
        ('2', 'Conélio Agripa'),
        ('3', 'Madame Elfrida Clagg'),
        ('4', 'Grogan Stump'),
        ('5', 'Glliver Pokeby'),
        ('6', 'Glanmore Peakes'),
        ('7', 'Hesper Stakey'),
        ('8', 'Derwent Shimpling'),
        ('9', 'Gunhilda Gorsemoor'),
        ('10', 'Burdock Muloon'),
        ('11', 'Herpo, o Sujo'),
        ('12', 'Merwyn, O Malicioso'),
        ('13', 'Adros, O Invenível'),
        ('14', 'Fulbert, O Medroso'),
        ('15', 'Paracelso'),
        ('16', 'Cliodna'),
        ('17', 'Morgana Le Fay'),
        ('18', 'Úrico, O Esquisitão'),
        ('19', 'Newt Scamander'),
        ('20', 'Wendelin Esquisita'),
        ('21', 'Stoddard Withers'),
        ('22', 'Circe'),
        ('23', 'Glenda Chitock'),
        ('24', 'Adalberto Waffling'),
        ('25', 'Perpétua Fancolurt'),
        ('26', 'Almérico Sawbridge'),
        ('27', 'Mirabella Plunkett'),
        ('28', 'Tilly Toke'),
        ('29', 'Arquibaldo Alderton'),
        ('30', 'Artemisia Lufkin'),
        ('31', 'Balfour Blane'),
        ('32', 'Bridgt Wenlock'),
        ('33', 'Beaumont Majorhands'),
        ('34', 'Donaghan Tremlett'),
        ('35', 'Bowman Wright'),
        ('36', 'Jocelina Wadcock'),
        ('37', 'Cassandra Vablatsk'),
        ('38', 'Chauncey Oldrige'),
        ('39', 'Guga Jones'),
        ('40', 'Carlota Pikstone'),
        ('41', 'Godric Gryffindor'),
        ('42', 'Crispin Cronk'),
        ('43', 'Ciprião Youdle'),
        ('44', 'Devlin Whitehorn'),
        ('45', 'Dunbar Oglethorpe'),
        ('46', 'Miranda Goshawk'),
        ('47', 'Edgar Stroulger'),
        ('48', 'Salazar Slytherin'),
        ('49', 'Elladora Ketteridge'),
        ('50', 'Musidora Barkwith'),
        ('51', 'Etherlred, O alerta'),
        ('52', 'Felix Summerbee'),
        ('53', 'Greta Catchlove'),
        ('54', 'Gaspar Shingleton'),
        ('55', 'Honoria Nutcombre'),
        ('56', 'Gideão Crumb'),
        ('57', 'Gifford Ollerton'),
        ('58', 'Glover Hipwoth'),
        ('59', 'Gregory Smarmy'),
        ('60', 'Laverne Montmorency'),
        ('61', 'Havelock Sweeting'),
        ('62', 'Ingnatia Wildsmith'),
        ('63', 'Herman Wintrigham'),
        ('64', 'Jacunda Sykes'),
        ('65', 'Gondolin Oliphant'),
        ('66', 'Flavio Belby'),
        ('67', 'Justus Piliwickle'),
        ('68', 'Kirley McComack'),
        ('69', 'Berti Bott'),
        ('70', 'Leopoldina Smethwyck'),
        ('71', 'Queen Maeve'),
        ('72', 'Helga Hufflepuff'),
        ('73', 'Mopsus'),
        ('74', 'Montague Knightley'),
        ('75', 'Mungo Bonham'),
        ('76', 'Myron Wagtai'),
        ('77', 'Norvel Twonk'),
        ('78', 'Orsino Beasmish'),
        ('79', 'Osvaldo Beasmish'),
        ('80', 'Beatrix Bloxam'),
        ('81', 'Quong Po'),
        ('82', 'Rowena Ravenclaw'),
        ('83', 'Rodrigo Plumpton'),
        ('84', 'Rolando Kegg'),
        ('85', 'Blenheim Stalk'),
        ('86', 'Dorcas Wellbeloved'),
        ('87', 'Tadeu Thurkell'),
        ('88', 'Celestina Warbeck'),
        ('89', 'Alberta Toohill'),
        ('90', 'Sacarissa Tugwood'),
        ('91', 'Wilfred Elphick'),
        ('92', 'Xavier Rastrick '),
        ('93', 'Heathcote Barbary '),
        ('94', 'Merton Graves'),
        ('95', 'Yadley Platt'),
        ('96', 'Hengiso Woodcoft'),
        ('97', 'Alberico Brynion'),
        ('98', 'Dymphna Furmage'),
        ('99', 'Daisy Dodderigde'),
        ('100', 'Harry Tiago Potter'),
        ('101', 'Alvo Percival Wulfrico Brian Dumbledore')
    ]
    shuffle(Figurinhas_Sapos_de_Chocolate)

    return Figurinhas_Sapos_de_Chocolate[0]